# SPDX-FileCopyrightText: 2024 MoonlightByte
# SPDX-License-Identifier: Fair-Source-1.0
# License: See LICENSE file in the repository root
# This software is subject to the terms of the Fair Source License.

"""
NeverEndingQuest module monster media closure utility.

Deterministic, provider-free placeholder JPEG generation for monster
media files that are missing from a module's ``media/monsters/`` directory.
Slugs are derived from monster JSON filename stems, not the monster name field.

The placeholder is a pre-computed minimal valid 1x1 grayscale JPEG that
passes ``check_monster_media()`` detection (file existence + ``.jpg`` extension).
No PIL/Pillow, no HTTP, no subprocess calls.
"""

import base64
import json
import os
from typing import Any, Dict, List

# ---------------------------------------------------------------------------
# Pre-computed minimal valid JPEG (1x1 grayscale, 155 bytes)
# Generated by build_minimal_jpeg(); verified to start with SOI (FF D8)
# and end with EOI (FF D9).  Any JPEG decoder will accept it.
# ---------------------------------------------------------------------------
_MINIMAL_JPEG_BASE64 = (
    "/9j/4AAQSkZJRgABAQAAAQABAAD/"
    "2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB"
    "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/"
    "wAALCAABAAEBAREA/"
    "8QAJgABAAAAAAAAAAAAAAAAAAAAABABAAAAAAAAAAAAAAAAAAAAAP/"
    "aAAgBAQAAPwAA/9k="
)

MINIMAL_JPEG_BASE64: str = _MINIMAL_JPEG_BASE64
"""Base64-encoded minimal valid JPEG byte stream (~155 bytes)."""

_MINIMAL_JPEG_BYTES: bytes = base64.b64decode(MINIMAL_JPEG_BASE64)
"""Decoded JPEG bytes cached for repeated writes."""


def close_monster_base_media(module_dir: str) -> Dict[str, Any]:
    """Write placeholder JPEG for every monster slug lacking ``media/monsters/``
    base media.

    Scans ``{module_dir}/monsters/*.json`` for monster slugs (filename stems),
    checks whether ``media/monsters/{slug}.jpg`` exists, and creates a
    placeholder for each missing slug.  Existing files are never overwritten.

    Args:
        module_dir: Absolute or relative path to the module root directory.

    Returns:
        A dict with:
          - ``created``: number of placeholder files written.
          - ``skipped``: number of pre-existing monster media files.
          - ``errors``: list of error message strings (empty on success).
    """
    created: int = 0
    skipped: int = 0
    errors: List[str] = []

    monsters_dir = os.path.join(module_dir, "monsters")
    media_dir = os.path.join(module_dir, "media", "monsters")

    # -- early exit if monsters directory is missing -------------------------
    if not os.path.isdir(monsters_dir):
        return {
            "created": created,
            "skipped": skipped,
            "errors": errors,
        }

    # -- collect monster slugs from JSON filenames ---------------------------
    try:
        entries = sorted(os.listdir(monsters_dir))
    except PermissionError as exc:
        errors.append(f"Cannot list {monsters_dir}: {exc}")
        return {
            "created": created,
            "skipped": skipped,
            "errors": errors,
        }

    slugs: List[str] = []
    for entry in entries:
        if not entry.endswith(".json"):
            continue
        # Ensure the file is valid JSON before treating it as a monster
        # (avoids writing placeholders for stray .json files like
        #  directory_listing.json or index.json).
        fpath = os.path.join(monsters_dir, entry)
        try:
            with open(fpath, "rb") as fh:
                raw = fh.read()
            # Quick validation: content must be a dict with a ``name``
            # key (universal across SRD 5e monster stat blocks).  This
            # filters out non-monster JSON files (index.json, etc.).
            data = json.loads(raw)
            if not isinstance(data, dict) or "name" not in data:
                continue
        except (json.JSONDecodeError, OSError):
            continue

        slug = entry[: -len(".json")]
        slugs.append(slug)

    if not slugs:
        return {
            "created": created,
            "skipped": skipped,
            "errors": errors,
        }

    # -- ensure media/monsters directory exists -------------------------------
    try:
        os.makedirs(media_dir, exist_ok=True)
    except OSError as exc:
        errors.append(f"Cannot create {media_dir}: {exc}")
        return {
            "created": created,
            "skipped": skipped,
            "errors": errors,
        }

    # -- write missing placeholders -------------------------------------------
    for slug in slugs:
        target = os.path.join(media_dir, f"{slug}.jpg")
        if os.path.exists(target):
            skipped += 1
            continue
        try:
            with open(target, "wb") as fh:
                fh.write(_MINIMAL_JPEG_BYTES)
            created += 1
        except OSError as exc:
            errors.append(f"Cannot write {target}: {exc}")

    return {
        "created": created,
        "skipped": skipped,
        "errors": errors,
    }
